export const host = "http://localhost:4000"
export const uploadImageRoute = `${host}/upload`
export const addPortfolioRoute = `${host}/addportfolio`
export const removePortfolioRoute = `${host}/removeportfolio`
export const displayAllPortfolioRoute = `${host}/allportfolio`
// export const listUserRoute = `${host}/listusers`
export const displayAlllistUsersRoute = `${host}/allusers`
export const removelistUsersRoute = `${host}/removeusers`
export const listBookingRoute = `${host}/allbookings`;
export const removeBookingRoute = `${host}/removebookings`
